# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f3be70c58c56bf1c66af3f0493b3f5a48cc060dab68f1ec39f06b6a1d6518f2b0d22d16d50a8a4acc38299657eee37b5f1810f08bca2666f2f17221d7e3dc91

test:
  secret_key_base: 981ea2353820b6a03016dadad4789091f019bc594fc608e2617ed66046de4bbb7938462e29b14bfb793facba60094d6dd75b37aeea9e14f19bffd71ddd2d9e39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
