# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 011751517cb09616c5e939db7fb4bc7be0e8876d24076b0ff99db21a7f7e46edfc561ee387dc29ceb8b5528c4735f3b325ff65a0ef39638df3b10b89f5664281

test:
  secret_key_base: cbe432f55035ff6993ecf4ecb09607147ee206b5c5d18accad6968d95afd7379f5d0d2624e501f00da52a9f1ffaf8e78b0e6a509cbe7348d7ff71278ef1c7927

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
