default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: ba
  username: ba
  password: ba
  port: 19000
  timeout: 30
  pool: 10

development:
  <<: *default
#  database: booking_analytics_development
#  username: postgres
#  password:
#  port: 5432

test:
  <<: *default
  database: booking_analytics_test

production:
  <<: *default

staging:
  <<: *default
