default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: ba
  username: ba
  password: ba
  port: 5435
  timeout: 30
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: booking_analytics_test

production:
  <<: *default

staging:
  <<: *default
