defaults: &defaults
  sessions:
    default:
      database: ba
      hosts:
        - localhost:19000
      options:
        pool_size: 35
        refresh_interval: 10
        timeout: 30

development:
  <<: *defaults

production:
  <<: *defaults

test:
  sessions:
    default:
      database: booking_analytics_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
